[package]
name = "fledge-server"
version = "0.1.0"
authors = ["Robin Miller <grenewodemiller@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
serde_json = "1.0"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.1.0"
cpython = "0.2"
log = "0.4"
env_logger = "0.5"